dist: trusty
language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.2
    - 7.3
    - nightly

before_install:
    - composer self-update
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
    - travis_retry composer update --prefer-dist

script: ./vendor/bin/phpunit

jobs:
    include:
        -   stage: Test
            env: COVERAGE
            php: 7.2
            before_script:
                - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
                - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
            script:
                - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
            after_script:
                - wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar
                - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

        -   stage: Code Quality
            env: CODING_STANDARD
            php: 7.2
            script:
                - ./vendor/bin/phpcs

        -   stage: Code Quality
            env: STATIC_ANALYSIS
            php: 7.2
            script:
                - ./vendor/bin/phpstan analyse

